version = 1

test_patterns = ["tests/**"]

exclude_patterns = [
    "dist/",
    ".github/"
]

dependency_file_paths = ["requirements.txt"]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
